### ISSUE TITLE
Create a connection instance?

### ISSUE THREAD

**Issue by arn4v** [faithoflifedev/obs_websocket#1]
When I use sqflite I always use the singleton pattern to create an instance of the connection and return the same instance if the openDB() function is called again and again in separate query function. Is there a way we can do the same with obs-websocket?

Can we make the connection a separate methods w/ a return statement?

**Comment by faithoflifedev** [comment]
Sorry for the delayed response.  For some reason the notification for this issue never reached me.  Are you still looking to solve this problem?  In my code that uses this library as a dependency, I store the connection in an instance variable in the object that I'm working with and refer to that variable.

There's no reason that I can think of for why you couldn't use obs-websocket with a singleton design pattern.  There are several ways to create [singletons in dart](https://stackoverflow.com/questions/12649573/how-do-you-build-a-singleton-in-dart).  It's really a design choice for you to make.

**Comment by faithoflifedev** [comment]
I'll close this off due to it's age.
