### ISSUE TITLE
Version 5.0.0 of the protocol?

### ISSUE THREAD

**Issue by Grummfy** [faithoflifedev/obs_websocket#13]
Hello,
any plan to implements v5 of protocol?

see https://github.com/obsproject/obs-websocket/blob/release/5.0.0/docs/generated/protocol.md 

thanks

**Comment by faithoflifedev** [comment]
Hi @Grummfy , yes the next release will most likely use v5.  It's just a matter of getting the time to implement the changes.

**Comment by Grummfy** [comment]
thanks.

**Comment by faithoflifedev** [comment]
HI @Grummfy ,

A pre-release is now available - https://pub.dev/packages/obs_websocket/versions/5.0.0-dev.1

I welcome your feedback.

**Comment by Grummfy** [comment]
thanks
