### ISSUE TITLE
feedback on pre 5.0.0

### ISSUE THREAD

**Issue by Grummfy** [faithoflifedev/obs_websocket#16]
hello,
here is some feedback, it's raw note, so it could be a bit rough to read

* I'm happy it's here and it's seems more modulable ;)
* could be nice to have a mapping between command and from the list coming from the protocol and the way to call them
    * GetVersion : obsWebSocket.general.getVersion(), obsWebSocket.general.version, obsWebSocket.send('GetVersion')
* some changelog guide could a helpful plus
* I find a bit distracting to have several method to do the same thing like general.version and general.getVersion or getSourceScreenshot and getScreenshot 

### request
* getScreenshot method => use GetSourceActive instead of GetSourceScreenshot
* saveScreenshot method => use GetSourceActive instead of SaveSourceScreenshot
for the request, it's seems to be all

### response
* SourceScreenshotResponse : imageData is a bool instead of a string or a Uint8List
* SceneListResponse : currentPreviewSceneName could be null
I didn't look yet to other response

### event
* I don't know why yet, but ExitStarted seems to have trouble to be added in the handler

## Missing element
* RequestBatch

Sorry I didn't got the time to go deeper. If I got time, I will try to make some MR. Thanks for the work

**Comment by faithoflifedev** [comment]
HI @Grummfy,

I just updated the pre-release.  I believe I resolved all the bug identified.  `RequestBatch` is on the todo list for the future.

**Comment by Grummfy** [comment]
Thanks,

In the list of scene, I have an issue currentPreviewSceneName should be nullable (in SceneListResponse). 

Strange thing, I don't know yet if it's related to my code but when I get screenshot, the SceneListResponse seems to receive it too

**Comment by Grummfy** [comment]
Well, it's seems this issue (related to screenshot) was in my code.

But I got another one, in web mode and once again I don't know if it is in my code or the lib or something else.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'src__util__enum')
    at load__packages__obs_websocket__src__request__ui_dart (ui.dart.lib.js:27:65)

```

Sorry not to have time to dig deeper

**Comment by faithoflifedev** [comment]
Sorry @Grummfy , I'd need a bit more context to be able to troubleshoot this.  Do you have a code snippet that I can use to generate the error?

**Comment by Grummfy** [comment]
Well, I try to do a basic case to reproduce it

```
Uncaught SyntaxError: Duplicate parameter name not allowed in this context
ui.dart.lib.js:27 Uncaught TypeError: Cannot read properties of undefined (reading 'src__util__enum')
    at load__packages__obs_websocket__src__request__ui_dart (ui.dart.lib.js:27:65)
    at Object.execCb (require.js:1696:33)
    at Module.check (require.js:883:51)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.<anonymous> (require.js:1139:34)
    at require.js:134:23
    at require.js:1189:21
    at each (require.js:59:31)
    at Module.emit (require.js:1188:17)
    at Module.check (require.js:938:30)
    at Module.enable (require.js:1176:22)
    at Module.init (require.js:788:26)
    at callGetModule (require.js:1203:63)
    at Object.completeLoad (require.js:1590:21)
    at HTMLScriptElement.onScriptLoad (require.js:1717:29)
```

with flutter web

and the code
```


import 'package:obs_websocket/obs_websocket.dart';

Future<void> main() async {


    ObsWebSocket obsWebSocket = await ObsWebSocket.connect(
        'ws://127.0.0.1:4455', password: 'abcabc', timeout: const Duration(seconds: 5)
    );

    print(await obsWebSocket.scenes.list());
    return obsWebSocket.close();

}

```

**Comment by faithoflifedev** [comment]
I think we've identified a bug in Flutter Web in how it processes the new `Enum` features of Dart 2.17.  It appears that if an `Enum` has more than one member, then Flutter Web throws an error in the generated Javascript.
