### ISSUE TITLE
Running a command throws uncatchable Exception

### ISSUE THREAD

**Issue by flooo6297** [faithoflifedev/obs_websocket#2]
When running a command and the obs websocket server cannot be reached, a WebSocketChannelException is thrown, that cannot be caught.

**Comment by faithoflifedev** [comment]
Hi @flooo6297 ,

You haven't given me much to work with.  

Have you tried simplifying your code? Here's a simplified example that does work assuming you have the right IP address for your OBS machine and that you have installed the [obs-websocket](https://github.com/Palakis/obs-websocket) plugin along with [OBS](https://obsproject.com/) on that machine.

```
import 'package:obs_websocket/obsWebsocket.dart';
import 'package:universal_io/io.dart';
import 'package:yaml/yaml.dart';

void main(List<String> args) async {
  final config = loadYaml(File('config.yaml').readAsStringSync());

  ObsWebSocket obsWebSocket = ObsWebSocket(
      connectUrl: config['host']);

  final authRequired = await obsWebSocket.getAuthRequired();

  if (authRequired.status) {
    await obsWebSocket.authenticate(authRequired, config['password']);
  }

  final status = await obsWebSocket.getStreamStatus();

  print('status: ${status.streaming}');
}
```

**Comment by flooo6297** [comment]
I'm sorry I haven't made it more clear. I'm going to elaborate a bit.
Let's say I'll start my dart programm, that creates the obsWebsocket Object, but obs isn"t running.
When I want to run an action, for example a low level command, that fetches all scenes, there is no way to check, if the plugin is connected to the obsWebsocket. If it is, everything runs fine, but if it isn't connected, because obs isn't running, it just throws an exception. And this exception cannot be caught by the user.

I hope I have made my problem more understandable

**Comment by faithoflifedev** [comment]
Thank you, this is definitely more helpful.  I'll look at adding this type of functionality as a feature to the next release.
