### ISSUE TITLE
bug stopRecording function

### ISSUE THREAD

**Issue by KyoungJoonKim** [faithoflifedev/obs_websocket#21]
I found bug about stopRecording function at version 2.4.4.
See source lib\src\obs_websocket_base.dart line 288.
I think it should be changed to StopRecordinging -> StopRecording.

Thank you.

**Comment by faithoflifedev** [comment]
Hello @KyoungJoonKim ,

Thanks for the feedback.  I've released an update, available at - https://pub.dev/packages/obs_websocket/versions/2.4.4-hotfix.1

I've move to the new v5.0.0 obs-websocket protocol for the main project, so there will be minimal updates on the old branch moving forward.
